kind: PersistentVolume
apiVersion: v1
metadata:
  name: odoo-addons
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/extra-addons"