apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-shop
  labels:
    app: odoo-shop
spec:
  selector:
    matchLabels:
      app: odoo-shop
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: frontend
    spec:
      containers:
        - image: odoo:10.0
          name: odoo-shop
          env:
          - name: USER
            value: odoo
          - name: PASSWORD
            value: odoo
          - name: HOST
            value: odoo-db
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo
          volumeMounts:
          - name: odoo-pvc
            mountPath: /var/lib/odoo
          - name: odoo-addons-space
            mountPath: /mnt/extra-addons
      volumes:
      - name: odoo-pvc
        emptyDir: {}
      - name: odoo-addons-space
        persistentVolumeClaim:
         claimName: odoo-addons-claim